trigger:
  branches:
    include:
      - main

pool:
  name: 'AseEj'

steps:
- task: UseJava@1
  inputs:
    version: '17'

- script: |
    echo "Android Assembly on Azure Storm-arm"
    ./gradlew assembleRelease

