variables:
  AseEj: $(Build.ArtifactStagingDirectory)/AseEj
  branches:
    include:
      - main

  vmImage: 'windows-latest' # or Ubuntu-latest

trigger:
  branches:
    include:
      - main

pool:
  name: 'Ase'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
  inputs:
    version: '17'

    echo "Android Assembly on Azure Storm-arm"
    ./gradlew assembleRelease

  inputs:
    targetType: 'inline'
    script: |
      echo "Yo Android SDK installation"
      echo y | sdkmanager --install 'platforms;android-30'
      echo y | sdkmanager --install 'build-tools;30.0.3'
  
    - script: |
        echo "Set Android SDK Path"
        echo "ANDROID_SDK_ROOT=$(ANDROID_HOME)" >> $GITHUB_ENV

