trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest' # or Ubuntu-latest

steps:
- task: UseJava@1
  inputs:
    version: '17'

- script: |
    echo "Android Assembly on Azure Storm-arm"
    ./gradlew assembleRelease

