name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Install Android SDK
      run: |
        echo "Installing Android SDK"
        yes | sdkmanager --install 'platforms;android-30'
        yes | sdkmanager --install 'build-tools;30.0.3'
    - name: Build Android
      run: |
        ./gradlew assembleRelease
